apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sosmed
  name: sosmed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sosmed
  strategy: {}
  template:
    metadata:
      labels:
        app: sosmed
    spec:
      containers:
      - image: ikanpaus/sosmed:v3
        name: sosmed
        ports:
        - containerPort: 80
        # contoh OS environment variable dari configmap
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: sosmed-configmap
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: sosmed-configmap
                key: DB_USER
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: sosmed-configmap
                key: DB_NAME
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: sosmed-secret
                key: DB_PASS