apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sosmed
  name: sosmed
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sosmed
  type: LoadBalancer
status:
  loadBalancer: {}