# Dynamic Provisioning
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: "gp2"
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce